name: Tests
on: [push]
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn test
